In [ ]:
# [i*2 for i in [1,2,3,4]]

[2, 4, 6, 8]

In [ ]:
# NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data
# structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python. 
# NumPy contains, among other things:

# ● A fast and efficient multidimensional array object ndarray.
# ● Functions for performing element-wise computations with arrays or mathematical
# operations between arrays.
# ● Tools for reading and writing array-based datasets to disk.
# ● Linear algebra operations, Fourier transform, and random number generation

In [ ]:
# The NumPy ndarray
# A Multidimensional Array Object One of the key features of NumPy is its N-dimensional array object, or ndarray, which is
# a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole
# blocks of data using similar syntax to the equivalent operations between scalar elements

In [ ]:
# Why Numpy?
# One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on
# large arrays of data. There are a number of reasons for this:
# ● NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s
# library of algorithms written in the C language can operate on this memory without any type checking or other overhead. 
# NumPy arrays also use much less memory than built-in Python sequences.
# ● NumPy operations perform complex computations on entire arrays without the need for Python for loops. 


# less memory required ( contiguous block)
# scientific and mathematical computations.(linear algebra operations ,fouries transform)
# fast computation
# computations without for loops
# can store and manipulate large data
#in data analysis is as a container for data to be passed between algorithms and libraries.

In [ ]:
# pip install numpy

In [ ]:
# Importing numpy as np
import numpy as np

In [139]:
# %%time
lst=[i for i in range(1,10000000)]

In [140]:
%%time
lst_2=[i*2 for i in lst]

CPU times: total: 547 ms
Wall time: 537 ms


In [145]:
arr1=np.array(lst)
type(arr1)

numpy.ndarray

In [144]:
%%time
arr1*2

CPU times: total: 15.6 ms
Wall time: 12.9 ms


array([       2,        4,        6, ..., 19999994, 19999996, 19999998])

In [ ]:
# arrays are more faster than python list.

In [ ]:
# arr takes less memory than python list

In [147]:
type(arr1)

numpy.ndarray

In [148]:
import sys
print(sys.getsizeof(lst))
print(sys.getsizeof(arr1))

89095160
40000108


In [ ]:
sys.getsizeof(arr1)/sys.getsizeof(lst)

0.44895938230539123

In [151]:
## How to create arrays 
# from list
#np.array
lst=[i for i in range(1,11)]
print('list is',lst,type(lst))
arr1=np.array(lst)
print('arr1 is',arr1,type(arr1))

list is [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>
arr1 is [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [159]:
# list(range(10,20,.2))
np.arange(10,20,.2)


array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4,
       16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6,
       18.8, 19. , 19.2, 19.4, 19.6, 19.8])

In [163]:
np_array = np.arange(10,20,0.5)
np_array

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [242]:
np.random.rand()

0.4935552745617101

In [243]:
np.random.rand(2,2)

array([[0.36809312, 0.83888607],
       [0.07282749, 0.9593901 ]])

In [244]:
np.random.rand(3,2)

array([[0.09669332, 0.88037409],
       [0.85730537, 0.9368516 ],
       [0.38413645, 0.56077382]])

In [245]:
_3d= np.random.rand(3,3,3)

In [247]:
_3d.ndim
_3d.size
_3d.shape

(3, 3, 3)

In [ ]:
import numpy as np

# Set a seed for reproducibility
# np.random.seed(41)

# 1. Random Integers
print("Random Integers:\n", np.random.randint(10, 20, size=(3, 2)))  # 2x3 array from 0 to 9

# 2. Random Floats (Uniform between 0 and 1)
print("\nRandom Floats:\n", np.random.rand(2, 3))  # 2x3 array from uniform[0, 1)

# 3. Random Floats (Normal distribution)
# print("\nNormal Distribution (mean=0, std=1):\n", np.random.randn(2, 3))  # standard normal

# 4. Random choice from a list
print("\nRandom Choice from [10, 20, 30]:\n", np.random.choice([10, 20, 30]))

# 5. Random permutation (shuffling a sequence)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("\nShuffled Array:\n", arr)

# # 6. Random permutation (returns a new array)
# print("\nRandom Permutation:\n", np.random.permutation([1, 2, 3, 4, 5]))

# # 7. Binomial Distribution (n=10, p=0.5)
# print("\nBinomial Distribution:\n", np.random.binomial(n=10, p=0.5, size=5))

# # 8. Poisson Distribution (lambda=3)
# print("\nPoisson Distribution:\n", np.random.poisson(lam=3, size=5))

# # 9. Exponential Distribution (scale=1.0)
# print("\nExponential Distribution:\n", np.random.exponential(scale=1.0, size=5))

# # 10. Beta Distribution (a=2.0, b=5.0)
# print("\nBeta Distribution:\n", np.random.beta(a=2.0, b=5.0, size=5))

# # 11. Gamma Distribution (shape=2.0, scale=1.0)
# print("\nGamma Distribution:\n", np.random.gamma(shape=2.0, scale=1.0, size=5))

# # 12. Uniform Distribution (between [low, high))
# print("\nUniform Distribution (2.0 to 5.0):\n", np.random.uniform(low=2.0, high=5.0, size=5))


Random Integers:
 [[10 13]
 [12 10]
 [11 13]]

Random Floats:
 [[0.60056724 0.92435824 0.78786441]
 [0.76383076 0.70297401 0.83393912]]

Random Choice from [10, 20, 30]:
 10

Shuffled Array:
 [5 3 1 4 2]


In [320]:
# dimension of an array : size ,shape ,ndim,itemsize
# create a random array of the 10 numbers between 10 to 20
arr1=np.random.randint(10,20,10)
print(arr1)
print(arr1.shape)  # shape of the arrau as tuple
print(arr1.ndim)  # dimension of array 
print(arr1.size) # how many elements are there

[14 17 16 11 15 12 11 15 13 12]
(10,)
1
10


In [329]:
# reshape
arr1=np.arange(12)
print(arr1)


arr2 = arr1.reshape(6,2,1)
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]]
(6, 2, 1)
12
3


In [ ]:
# 3,3,4
arr1=np.arange(36)
print(arr1)
arr2=arr1.reshape(3,3,4)
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

In [ ]:
# axis :
# 2d   ===>axis=0 : Row  (Horizontal)
#          axis=1 : Column  (Vertical)

In [330]:
####  Arithmatic Operation on an array : 0 axis ,axis 1..
arr1=np.arange(10)
print(arr1)
print(arr1.sum())
print(arr1.prod())
print(arr1.mean())

[0 1 2 3 4 5 6 7 8 9]
45
0
4.5


In [347]:
#2d axis0 ==>row   axis1==>column
arr1=np.arange(1,13).reshape(3,4)
print(arr1)
print(arr1.sum()) # all elements sum
print(arr1.sum(axis=0)) # rowise
print(arr1.sum(axis=1))  # columnwise sum


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


In [348]:
print(arr1.prod()) # all elements sum
print(arr1.prod(axis=0)) # rowise
print(arr1.prod(axis=1))  # columnwise sum

479001600
[ 45 120 231 384]
[   24  1680 11880]


In [349]:
arr1.max()

12

In [350]:
print(arr1.max(axis=0))

[ 9 10 11 12]


In [351]:
print(arr1.max(axis=1))

[ 4  8 12]


In [352]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [353]:
print(arr1.cumsum(axis=0))

[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]]


In [354]:
print(arr1.cumsum(axis=1))

[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


In [357]:
print(arr1.cumprod(axis=0))

[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]


In [358]:
# arr1=np.random.randint(10,20,12).reshape(2,2,3)
# arr1

In [360]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [359]:
print(arr1.mean(axis=0)) 

[5. 6. 7. 8.]


In [361]:
print(arr1.mean(axis=1)) # 2,2,3==>2,3

[ 2.5  6.5 10.5]


In [ ]:
#prod ,max,min,cumsum,cumprod ,argmax,argmin ,mean ,std,var

In [362]:
import numpy as np

In [363]:
### Some Homogeneous arrays 

In [364]:
arr1=np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(arr1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [365]:
# array of zeros : creates  the array of zeros for the given shape
zero=np.zeros((10,10))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [366]:
# ones
one=np.ones((10,10))
print(one)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [371]:
# identity :1 on diagonal and zero others : sqaure
identity=np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [375]:
# eye will create an array of non sqaure dimension
arrr_1=np.eye(10,10, k=4)
print(arrr_1)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [379]:
# full
full_1=np.full((3,4),5)
print(full_1)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [380]:
#diag
arr1=np.diag([1,2,3,4,5])
print(arr1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [381]:
arr1=np.diag([1,2,3,4,5],k=-1)
print(arr1)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [382]:
arr1=np.arange(1,6)
print(arr1)

[1 2 3 4 5]


In [383]:
arr_diag=np.diag(arr1)
print(arr_diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# when we pass a list or tuple or 1d array to diag function it will
# return a diagonal array with the list or tuple or 1d array elements on 
# doigonal but if we pass multi dim array in diag function it will return
# the kth diagonal where n is the second parameter .
# default k=0

In [ ]:
##### Some arithmatic on arrays +,-,*,/

In [ ]:
np.random.seed(5) # initiliza the random no generation
arr1=np.random.randint(10,20,12).reshape(4,3)
print(arr1)

In [386]:
np.random.seed(6)
arr1=np.random.randint(10,20,12).reshape(4,3)
print(arr1)

[[19 13 14]
 [10 19 11]
 [19 11 14]
 [11 18 12]]


In [387]:
print(arr1*2)

[[38 26 28]
 [20 38 22]
 [38 22 28]
 [22 36 24]]


In [388]:
print(arr1//2)

[[9 6 7]
 [5 9 5]
 [9 5 7]
 [5 9 6]]


In [ ]:
lst=[i for i in range(10,30)]
print(lst)

In [ ]:
print([i*2 for i in lst])

In [ ]:
print(arr1+arr2)

In [ ]:
# Broadcasting :
# Broadcasting is used for arithmatic on arrays having diff dimensions or diff shapes
# The two arrays having same dimension can be broadcasted if the corresponding
# dimensionvalue is either same or one of the value is equal to 1.
# 2,1,4
# 1,2,4
# If the dim of the arrays is not same then in broadcasting 1 will be appended
# on the left hand side/prepended 
#in the shape  of the array having minimum dimension.
# 2,1,3,3 
# 1,1 3,3

In [393]:
# 2,1,4
# 1,2,4
arr1=np.random.randint(10,20,8).reshape(2,4)
arr2=np.random.randint(10,20,8).reshape(2,4)
print('arr1 - ',arr1)
print('*********************')
print('arr2 - ',arr2)

arr1 -  [[10 13 17 14]
 [18 11 12 14]]
*********************
arr2 -  [[11 15 15 16]
 [11 19 10 15]]


In [391]:
arr1+arr2

array([[34, 26, 24, 30],
       [34, 34, 35, 31]])

In [394]:
arr1%arr2

array([[10, 13,  2, 14],
       [ 7, 11,  2, 14]])

In [ ]:
arr1-arr2

array([[ 4,  4,  0,  4],
       [ 2, -4, -3, -5]])

In [ ]:
#2,1,3,3 
#3,3
# same as above

In [ ]:
##### Indexing and slicing on array

In [ ]:
arr1=np.arange(30,40,0.5)
print(arr1)

In [ ]:
arr1[3]

In [ ]:
arr1[-1]

In [ ]:
arr1[4:]

In [ ]:
arr1[::-1]

In [ ]:
arr1=np.random.randint(1,10,12).reshape(3,4)
print(arr1)

In [ ]:
arr1[2] # axis=0 row ,axis=1 column

In [ ]:
arr1[1][2]

In [ ]:
arr1[1,2]

In [ ]:
arr1[:,2]

In [ ]:
arr1[:,1:]

In [ ]:
arr1=np.random.randint(1,10,24).reshape(2,3,4)
print(arr1)

In [ ]:
arr1[-1]

In [ ]:
arr1[1,2,3]

In [ ]:
print(arr1)

In [ ]:
arr1[:,0,3]

In [ ]:
arr1[:,:,3]

In [ ]:
print(arr1)

In [ ]:
arr1[1:,2:,2:]

In [ ]:
# diff bet array and list 
# array are faster than list
# array takes lesser memory than list
# array can only hold homogeneous data while list can hold heterogeneous data also

In [ ]:
lst=[1,2,5,6,11,34,56,77]
print(lst)

In [ ]:
lst[3:6]=5,

In [ ]:
print(lst)

In [ ]:
arr1=np.array([1,2,5,6,11,34,56,77])
print(arr1)

In [ ]:
arr1[3:6]=5

In [ ]:
print(arr1)

In [ ]:
lst=[1,2,5,6,11,34,56,77]
print(lst)

In [ ]:
lst_slice=lst[2:5]
print(lst_slice)

In [ ]:
lst[2]=100

In [ ]:
print(lst,lst_slice)

In [ ]:
arr1=np.array([1,2,5,6,11,34,56,77])
print(arr1)

In [ ]:
arr_slice=arr1[2:5]
print(arr_slice)

In [ ]:
arr1[2]=100

In [ ]:
print(arr1,arr_slice)

In [ ]:
# arr_slice is just a view object of the original array so whetever changes we will
# make in arr_slice will be reflected in org array also and vice versa.

In [ ]:
import numpy as np
arr1=np.array([1,2,5,6,11,34,56,77])
print(arr1)
arr_slice=(arr1[2:5]).copy()  #shallow copy
print(arr_slice)

In [ ]:
arr1[3]=100
print(arr1)
print(arr_slice)

In [ ]:
# Boolean indexing in array
arr1=np.random.randint(5,15,12).reshape(4,3)
print(arr1)

In [ ]:
arr1[2,2]

In [ ]:
arr1>8

In [ ]:
arr2=arr1[arr1>8]
print(arr2)

In [ ]:
# multidim to 1d
arr1.flatten()

In [ ]:
### Some more ways to createc arrays 

In [ ]:
# arange :  (a,b,c)  c can be float also  1d array
arr1=np.arange(10,20,0.5)
print(arr1)

In [ ]:
# linspace   # it will return the 50 equidistant points in given range defaultly and 
# endpoint is inclusive
arr2=np.linspace(10,20,40,endpoint=False,retstep=True)
print(arr2)

In [ ]:
arr2=np.linspace((1,2),(3,4),num=10,endpoint=False,retstep=True,axis=1)
print(arr2)

In [ ]:
# random 
arr1=np.random.randint(12,20,20)
print(arr1)


In [ ]:
# random.rand - floating values 0 to 1
arr1=np.random.rand(2,3)
print(arr1*10+50) # 0 to 10
               # 50 to 60

In [ ]:
# random.randn : generates the random numbers array of given shape following normal distribution.
arr1=np.random.randn(10)
print(arr1)

In [ ]:
# random.choice
arr1=np.random.randint(10,20,5)
print(arr1)

In [ ]:
np.random.choice(arr1,(2,3))

In [ ]:
arr1=np.array(['IT','HR','Finance','Account'])
print(arr1)
print(np.random.choice(arr1))

In [ ]:
#np.random.seed(11)   # intitiate the random no generation
np.random.seed(3)
arr1=np.random.randint(10,20,5)
print(arr1)

In [ ]:
#random.permutation
arr1=np.random.randint(10,20,10).reshape(5,2)
print(arr1)

In [ ]:
arr2=np.random.permutation(arr1)
print(arr2)

In [ ]:
arr3=arr2.transpose()  # rows to column and columns to rows.
print(arr3)

In [ ]:
#transpose()

In [ ]:
#flatten, insert ,append ,sort in numpy array

In [ ]:
arr1=np.random.randint(10,20,10).reshape(5,2)
print(arr1)

In [ ]:
arr3=np.insert(arr1,3,[2,3],axis=0)  # arr1,where,what,axis=0,1
print(arr3)

In [ ]:
arr3=np.insert(arr1,1,[2,3,4,5,6],axis=1)
print(arr3)

In [ ]:
arr1=np.random.randint(1,10,6).reshape(2,3)
arr2=np.random.randint(1,10,6).reshape(2,3)
print(arr1)
print(arr2)

In [ ]:
arr3=np.append(arr1,arr2,axis=1)
print(arr3)

In [ ]:
# sorting axis=0 and axis=1
arr1=np.random.randint(1,10,6).reshape(2,3)
print(arr1)

In [ ]:
arr1.sort(axis=0)  #comparing the values of rows
arr1


In [ ]:
arr1.sort(axis=1)  #comparing the values of rows
arr1
# changes oriiginal array

In [ ]:
# lst=[1,2,3,4,5,5,5,5,6,6,6,7,7,6,8,5,4,6,5,3,5,34,34,3,45,11,23,12,23,42]

In [ ]:
#np.where

In [ ]:
arr1=np.arange(6).reshape(2,3)
print(arr1)

In [ ]:
np.where(arr1>2,"yes","no")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Read the image as a NumPy array
img = mpimg.imread(r'D:\local_synced\workspace\Batches\B10\Attendance.png')  # or .png, .jpeg

print("Image shape:", img.shape)
print("Image dtype:", img.dtype)

# Display image
plt.imshow(img)
plt.axis('off')
plt.show()


In [ ]:
img